services:
  destinationdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: destinationdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
